name: provider_sidecar
description: Help developers better manage state with provider.
version: 1.0.0
homepage: https://github.com/Hu-Wentao

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: