name: provider_sidecar
description: Help developers better manage state with provider.
version: 1.2.1
homepage: https://github.com/Hu-Wentao

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
#  build_runner:
#  freezed:
flutter: